{{- if .Values.PVC -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ .Values.nameService }}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.PVC.storageClassName}}
  volumeMode: Filesystem

{{- end -}}

---