apiVersion: v1
kind: Service
metadata:
  name: archivist-es
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: {{ .Values.elasticsearch.service.port }}
  selector:
    app: archivist-es
