vaultwarden:
  Image: 'vaultwarden/server:latest' 
  Service:
      port: 80
  PVC:
      storageClassName: microk8s-hostpath
      capacity: 1Gi
      Enable: true
  Ingress:
    Host: vault.thelmalouise.ddns.net
    prefix: ""
  Volumes:
        config:
          type: volumenClain
          mountPath: /data