{{- range $key, $val := .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    nombre: {{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key  }}
  template:
    metadata:
      labels:
        app: {{ $key  }}
    spec:
      containers:
        - name: {{ $key  }}
          image: {{ $val.Image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{  $val.Service.port }}
          env:
          {{- range $key, $value := $val.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          volumeMounts:
            {{- range $name, $data :=  $val.Volumes }}
            - name: {{ $name }}
              mountPath: {{ $data.mountPath }}
            {{- end }}
            {{- if or (eq $key "sonarr") ( eq $key "radarr")  ( eq $key "prowlarr") }}
            - name: config-volume
              mountPath: /config_example
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{  $val.Service.port }}
            initialDelaySeconds: 30
            periodSeconds: {{ $val.readinessProbe.Seconds  }}
          livenessProbe:
            tcpSocket:
              port: {{  $val.Service.port }}
            initialDelaySeconds: 30
            periodSeconds: {{ $val.livenessProbe.Seconds }}
          resources: {}
          {{- if or (eq $key "sonarr") ( eq $key "radarr") ( eq $key "prowlarr") }}
          lifecycle:
            postStart:
              exec:
                command: ['sh', '-c', 'cp /config_example/config.xml /config/config.xml'] 
          {{- end }}
          {{- if eq $key "calibre" }}
          lifecycle:
            postStart:
              exec:
                command: ['sh', '-c', 'wget -LO https://github.com/janeczku/calibre-web/raw/master/library/metadata.db' ] 
          {{- end }}

      volumes:
      {{- range $name, $data :=  $val.Volumes }}
      - name: {{ $name }}
      {{- if eq $data.type  "volumenClain" }}
        persistentVolumeClaim:
          claimName: pvc-{{ $key }}
      {{- else if eq  $data.type  "nfs" }}
        nfs:
            server: {{ $data.server }}
            path: {{ $data.path }}
      {{- end }}
      {{- end }}
      {{- if or (eq $key "sonarr") ( eq $key "radarr")  ( eq $key "prowlarr") }}
      - name: config-volume
        configMap:
          name: {{$key}}-config
      {{- end }}
---
{{- end }} 





