{{- range $key, $val := .Values }}
{{- if eq $val.Ingress.Enable true }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $key }}-ingress
  labels:
    nombre: {{ $key }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if eq $val.Ingress.EnableOauth true}}
    nginx.ingress.kubernetes.io/auth-response-headers: >-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-signin: >-
      https://{{ $val.Ingress.Host }}/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
    nginx.ingress.kubernetes.io/auth-url: >-
      http://ak-outpost-authentik-embedded-outpost.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $val.Ingress.Host }}
      http:
        paths:
        - path: /{{ $val.Ingress.prefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $key }}-svc
              port:
                number: {{ $val.Service.port }}
---
{{- end }}
{{- end }}
