apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name  }}
  template:
    metadata:
      labels:
        app: {{ .Values.name  }}
    spec:
      containers:
        - name: {{ .Values.name  }}
          image: {{ .Values.Image }}
          ports:
            - containerPort: {{ .Values.Service.portWeb }}
            - containerPort: {{ .Values.Service.portBack }}
          volumeMounts:
            {{- range $name, $data :=  .Values.Volumes }}
            - name: {{ $name }}
              mountPath: {{ $data.mountPath }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{  .Values.Service.portWeb }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{  .Values.Service.portWeb }}
            initialDelaySeconds: 15
            periodSeconds: 10

      volumes:
      {{- range $name, $data :=  .Values.Volumes }}
      - name: {{ $name }}
      {{- if eq $data.type  "volumenClain" }}
        persistentVolumeClaim:
          claimName: pvc-{{ $.Values.name }}
      {{- else if eq  $data.type  "nfs" }}
        nfs:
            server: {{ $data.server }}
            path: {{ $data.path }}
      {{- end }}
      {{- end }}






