kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ .Values.name }}
  labels:
    nombre: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  resources:
    requests:
      storage: {{ .Values.PVC.capacity}}
  storageClassName: {{ .Values.PVC.storageClassName}}

