sonarr:
  Image: 'lscr.io/linuxserver/sonarr:latest' 
  Service:
      port: 7878
  PVC:
      storageClassName: microk8s-hostpath
      capacity: 1gb
  Ingress:
    Host: app.thelmalouise.ddns.net
    prefix: sonarr
  Volumes:
        config:
          type: volumenClain
          mountPath: /config
        serie:
          type: nfs
          mountPath: /movies
          server: 192.168.18.10
          path: /volume1/Multimedia/Peliculas
        descargas:
          type: nfs 
          mountPath: /downloads
          server: 192.168.18.10
          path: /volume1/Descargas
  

radarr:
  Image: 'lscr.io/linuxserver/radarr:latest' 
  Service:
      port: 8989
  PVC:
      storageClassName: microk8s-hostpath
      capacity: 1gb
  Ingress:
    Host: app.thelmalouise.ddns.net
    prefix: radarr
  Volumes:
        config:
          type: volumenClain
          mountPath: /config
        serie:
          type: nfs
          mountPath: /movies
          server: 192.168.18.10
          path: /volume1/Multimedia/Peliculas
        descargas:
          type: nfs 
          mountPath: /downloads
          server: 192.168.18.10
          path: /volume1/Descargas