nameService: 'radarr'

Image: '' 

Service:
    port: 0
PVC:
    storageClassName: microk8s-hostpath
Ingress:
    host: ''
Volumes:
      config:
        type: volumenClain
        mountPath: /config
      serie:
        type: nfs
        mountPath: /movies
        server: 192.168.18.10
        path: /volume1/Multimedia/Peliculas
      descargas:
        type: nfs 
        mountPath: /downloads
        server: 192.168.18.10
        path: /volume1/Descargas