apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.discordMusicBot.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.discordMusicBot.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.discordMusicBot.name }}
    spec:
      containers:
        - name: {{ .Values.discordMusicBot.containerName }}
          image: "{{ .Values.image.discordMusicBot.repository }}:{{ .Values.image.discordMusicBot.tag }}"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config.js
              subPath: config.js
          restartPolicy: Always
      volumes:
        - name: config-volume
          hostPath:
            path: {{ .Values.discordMusicBot.configPath }}