{{- range $key, $val := .Values }}
{{- if or (eq $key "sonarr") ( eq $key "radarr") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$key}}-config
  labels:
    app: {{$key}}-config
data:
  {{- $val.ConfigMap | toYaml | nindent 2 }}
---
{{- end }} 
{{- end }} 
