{{- range $key, $val := .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    nombre: {{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key  }}
  template:
    metadata:
      labels:
        app: {{ $key  }}
    spec:
      containers:
        - name: {{ $key  }}
          image: {{ $val.Image }}
          {{- if $key eq 'sonarr' or $key eq 'radarr' -}}
          command: ['sh', '-c', 'cp /config_example/config.xml /config/config.xml']
          {{- end -}}
          ports:
            - containerPort: {{  $val.Service.port }}
          volumeMounts:
            {{- range $name, $data :=  $val.Volumes }}
            - name: {{ $name }}
              mountPath: {{ $data.mountPath }}
            {{- end }}
            - name: config-volume
              mountPath: /config_example
          readinessProbe:
            tcpSocket:
              port: {{  $val.Service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{  $val.Service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10

      volumes:
      {{- range $name, $data :=  $val.Volumes }}
      - name: {{ $name }}
      {{- if eq $data.type  "volumenClain" }}
        persistentVolumeClaim:
          claimName: pvc-{{ $key }}
      {{- else if eq  $data.type  "nfs" }}
        nfs:
            server: {{ $data.server }}
            path: {{ $data.path }}
      {{- end }}
      {{- end }}
      {{- if $key eq sonarr or $key eq radarr -}}
      - name: config-volume
        configMap:
          name: {{$key}}-config
      {{- end -}}
---
{{- end }} 





