youtube:
  Image: 'tzahi12345/youtubedl-material:latest'
  Service:
      port: 17442
  env:
    ytdl_mongodb_connection_string: 'mongodb://192.168.18.10:27017'
    ytdl_use_local_db: 'false'
    write_ytdl_config: 'true'
    ytdl_multi_user_mode: true
    ytdl_auth_method: 'ldap'
    ytdl_allow_registration: false

  PVC:
      storageClassName:  microk8s-hostpath
      capacity: 1Gi
      Enable: true
  readinessProbe: 
    Seconds: 30
  livenessProbe: 
    Seconds: 30
  Ingress:
    Enable: true
    Host: yt.thelmalouise.ddns.net
    prefix: ""
  Volumes:
        config:
          type: volumenClain
          mountPath: /config
        appdata:
          type: nfs 
          mountPath: /app/appdata
          server: 192.168.18.10
          path: /volume1/Multimedia/Youtube/appdata
        audio:
          type: nfs 
          mountPath: /app/audio
          server: 192.168.18.10
          path: /volume1/Multimedia/Youtube/audio
        video:
          type: nfs 
          mountPath: /app/video
          server: 192.168.18.10
          path: /volume1/Multimedia/Youtube/video
        subscriptions:
          type: nfs 
          mountPath: /app/subscriptions
          server: 192.168.18.10
          path: /volume1/Multimedia/Youtube/subscriptions
        users:
          type: nfs 
          mountPath: /app/users
          server: 192.168.18.10
          path: /volume1/Multimedia/Youtube/users
  ConfigMap:
    default.json : |
      {
      "YoutubeDLMaterial": {
        "Host": {
          "url": "http://example.com",
          "port": "17442"
        },
        "Downloader": {
          "path-audio": "audio/",
          "path-video": "video/",
          "default_file_output": "",
          "use_youtubedl_archive": true,
          "custom_args": "",
          "include_thumbnail": true,
          "include_metadata": true,
          "max_concurrent_downloads": 5,
          "download_rate_limit": ""
        },
        "Extra": {
          "title_top": "YoutubeDL-Material",
          "file_manager_enabled": true,
          "allow_quality_select": true,
          "download_only_mode": false,
          "force_autoplay": false,
          "enable_downloads_manager": true,
          "allow_playlist_categorization": true,
          "enable_notifications": true,
          "enable_all_notifications": true,
          "allowed_notification_types": [],
          "enable_rss_feed": false
        },
        "API": {
          "use_API_key": false,
          "API_key": "",
          "use_youtube_API": false,
          "youtube_API_key": "",
          "twitch_auto_download_chat": false,
          "use_sponsorblock_API": false,
          "generate_NFO_files": false,
          "use_ntfy_API": false,
          "ntfy_topic_URL": "",
          "use_gotify_API": false,
          "gotify_server_URL": "",
          "gotify_app_token": "",
          "use_telegram_API": false,
          "telegram_bot_token": "",
          "telegram_chat_id": "",
          "telegram_webhook_proxy": "",
          "webhook_URL": "",
          "discord_webhook_URL": "",
          "slack_webhook_URL": ""
        },
        "Themes": {
          "default_theme": "dark",
          "allow_theme_change": true
        },
        "Subscriptions": {
          "allow_subscriptions": true,
          "subscriptions_base_path": "subscriptions/",
          "subscriptions_check_interval": "86400",
          "redownload_fresh_uploads": false
        },
        "Users": {
          "base_path": "users/",
          "allow_registration": false,
          "auth_method": "ldap",
          "ldap_config": {
            "url": "ldap://localhost:389",
            "bindDN": "cn=root",
            "bindCredentials": "secret",
            "searchBase": "ou=passport-ldapauth",
            "searchFilter": "(uid={{username}})"
          }
        },
        "Database": {
          "use_local_db": false,
          "mongodb_connection_string": "mongodb://192.168.18.10:27017"
        },
        "Advanced": {
          "default_downloader": "yt-dlp",
          "use_default_downloading_agent": true,
          "custom_downloading_agent": "",
          "multi_user_mode": true,
          "allow_advanced_download": false,
          "use_cookies": false,
          "jwt_expiration": 86400,
          "logger_level": "info"
        }
      }
      }