name: Deploy All Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runner:
        type: string
        default: self-hosted

jobs:
  find-and-deploy-charts:
    runs-on: ${{inputs.runner}}
    outputs:
      chart-paths: ${{ steps.set-chart-paths.outputs.chart-paths }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find All Chart Directories
        id: set-chart-paths
        run: |
          # Encuentra todas las carpetas que comienzan con "chart-" y guárdalas en un array
          chart_paths=$(find . -type d -name "chart-*")
          chart_paths=$(echo "${chart_paths}" | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "::set-output name=chart-paths::${chart_paths}"

    
  deploy-charts:
    needs: [find-and-deploy-charts]
    strategy:
      matrix:
        chart-path: ${{ fromJson(needs.find-and-deploy-charts.outputs.chart-paths) }}
    uses: ZundereneWork/reusables-workflow/.github/workflows/deploy-helm.yml@main
    with:
      chart-path: ${{ matrix.chart-path }}
        
      
        
