name: Deploy All Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  find-and-deploy-charts:
    runs-on: self-hosted

    outputs:
      chart_data: ${{ steps.set-chart.outputs.chart_data }}
      

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find All Chart Directories
        id: set-chart
        run: |
          # Buscar carpetas que comienzan con "chart-"
          folders=$(find . -type d -name 'chart-*' -printf '%P\n')

          # Convertir la lista de carpetas en un array de JSON
          json=$(echo "$folders" | jq -R . | jq -s .)

          # Guardar en un archivo JSON
          echo "$json" > chart-folders.json

          echo "JSON generado en 'chart-folders.json':"
          cat chart-folders.json

          echo "chart-data=$json" >> $GITHUB_OUTPUT

      - name: Print Chart Data (Debugging)
        run: |
           echo "Chart Data: ${{ steps.set-chart.outputs.chart-data }}"
  
      - name: Fail if Chart Data is Empty
        if: ${{ steps.set-chart.outputs.chart-data == '[]' || steps.set-chart.outputs.chart-data == '' }}
        run: |
            echo "No charts found with the prefix 'chart-'. Exiting."
            exit 1

    
  deploy-charts:
    needs: [find-and-deploy-charts]
    strategy:
      matrix:
        chart: ${{ fromJson(needs.find-and-deploy-charts.outputs.chart_data) }}
    uses: ZundereneWork/reusables-workflow/.github/workflows/deploy-helm.yml@main
    with:
      namespace: ${{ matrix.chart.release_name }}
      release_name: ${{ matrix.chart.release_name }}
      chart: ${{ matrix.chart.chart_path }}
        
      
        
