name: Deploy All Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runner:
        type: string
        default: self-hosted

jobs:
  find-and-deploy-charts:
    runs-on: ${{inputs.runner}}
    outputs:
      chart_data: ${{ steps.set-chart.outputs.chart_data }}
      

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find All Chart Directories
        id: set-chart
        run: |
          chart_data=$(find . -type d -name "chart-*" | while read chart; do
            release_name=$(basename "$chart" | sed 's/^chart-//')
            echo "{\"chart_path\": \"$chart\", \"release_name\": \"$release_name\"}"
          done | jq -s .)
          echo "::set-output name=chart-data::$chart_data"

    
  deploy-charts:
    needs: [find-and-deploy-charts]
    strategy:
      matrix:
        chart: ${{ fromJson(needs.find-and-deploy-charts.outputs.chart_data) }}
    uses: ZundereneWork/reusables-workflow/.github/workflows/deploy-helm.yml@main
    with:
      namespace: ${{ matrix.chart.release_name }}
      release_name: ${{ matrix.chart.release_name }}
      chart: ${{ matrix.chart.chart_path }}
        
      
        
