name: Deploy All Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  find-and-deploy-charts:
    runs-on: self-hosted

    outputs:
      chart_data: ${{ steps.set-chart.outputs.chart_data }}
      

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find All Chart Directories
        id: set-chart
        run: |
          chart_data=$(find . -type d -name "chart-*" | while read chart; do
            release_name=$(basename "$chart" | sed 's/^chart-//')
            echo "{\"chart_path\": \"$chart\", \"release_name\": \"$release_name\"}"
          done | jq -s .)
          echo "::save-state name=chart-data::$chart_data"

      - name: Print Chart Data (Debugging)
        run: |
           echo "Chart Data: ${{ steps.set-chart.outputs.chart-data }}"
  
      - name: Fail if Chart Data is Empty
        if: ${{ steps.set-chart.outputs.chart-data == '[]' || steps.set-chart.outputs.chart-data == '' }}
        run: |
            echo "No charts found with the prefix 'chart-'. Exiting."
            exit 1

    
  deploy-charts:
    needs: [find-and-deploy-charts]
    strategy:
      matrix:
        chart: ${{ fromJson(needs.find-and-deploy-charts.outputs.chart_data) }}
    uses: ZundereneWork/reusables-workflow/.github/workflows/deploy-helm.yml@main
    with:
      namespace: ${{ matrix.chart.release_name }}
      release_name: ${{ matrix.chart.release_name }}
      chart: ${{ matrix.chart.chart_path }}
        
      
        
